apiVersion: apps/v1
kind: Deployment
metadata:
  name: wecod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wecod
  template:
    metadata:
      labels:
        app: wecod
    spec:
      containers:
      - image: okteto.dev/wecod:latest
        name: wecod
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a947a326-cca4-421e-b3b6-d880a2d9d5ab"
        - name: Vless_Path
          value: "/gbvcdtcvexwn"
        - name: Vmess_UUID
          value: "a947a326-cca4-421e-b3b6-d880a2d9d5ab"
        - name: Vmess_Path
          value: "/kmnvtdxeskhotx"
        - name: Share_Path
          value: "/v2link"
