apiVersion: apps/v1
kind: Deployment
metadata:
  name: kervok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kervok
  template:
    metadata:
      labels:
        app: kervok
    spec:
      containers:
      - image: okteto.dev/kervok:latest
        name: kervok
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1ed6dd68-cdc0-47eb-b83c-d0c105186f2f"
        - name: Vless_Path
          value: "/kmthvfdxserdx"
        - name: Vmess_UUID
          value: "1ed6dd68-cdc0-47eb-b83c-d0c105186f2f"
        - name: Vmess_Path
          value: "/txcswzbgezkhotx"
        - name: Share_Path
          value: "/v2link"
