apiVersion: apps/v1
kind: Deployment
metadata:
  name: geet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geet
  template:
    metadata:
      labels:
        app: geet
    spec:
      containers:
      - image: okteto.dev/geet:latest
        name: geet
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d2b15469-086a-4445-bb3e-bcfc3f2c6cde"
        - name: Vless_Path
          value: "/kmtcvrvknygrdx"
        - name: Vmess_UUID
          value: "d2b15469-086a-4445-bb3e-bcfc3f2c6cde"
        - name: Vmess_Path
          value: "/fdygvcrxezkhotx"
        - name: Share_Path
          value: "/v2link"
