apiVersion: apps/v1
kind: Deployment
metadata:
  name: giod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giod
  template:
    metadata:
      labels:
        app: giod
    spec:
      containers:
      - image: okteto.dev/giod:latest
        name: giod
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4883d285-caa4-4400-ae10-5b2d0d4f7844"
        - name: Vless_Path
          value: "/knbvttcvexwn"
        - name: Vmess_UUID
          value: "4883d285-caa4-4400-ae10-5b2d0d4f7844"
        - name: Vmess_Path
          value: "/ygctfdxeskhotx"
        - name: Share_Path
          value: "/v2link"
